"use client";

import { km2 } from "@/lib/report";

const CLASS_COLOR: Record<string, string> = {
  urban_growth: "#c46a5a",
  vegetation_loss: "#cb9a54",
  vegetation_gain: "#8c9258",
  water_change: "#5a8fc4",
  bare_soil: "#b7bd90",
  unknown: "#757847",
};

export type ReportModel = {
  kind: string;
  title: string;
  subtitle?: string;
  dateRange?: string;
  meta: { label: string; value: string }[];
  mapImage?: string | null;
  stats?: { label: string; value: string }[];
  classBreakdown?: { class: string; area_m2: number }[];
  footerNote?: string;
};

// ReportDoc renders a branded, printable report. It is normally hidden and only
// becomes visible under @media print (see globals.css .report-print rules), so
// browser "Save as PDF" produces a clean single document.
export function ReportDoc({ model }: { model: ReportModel }) {
  const maxClass = Math.max(1, ...(model.classBreakdown ?? []).map((c) => c.area_m2));
  return (
    <div className="report-print" aria-hidden>
      <div className="report-page">
        {/* Header */}
        <div className="report-head">
          <div>
            <div className="report-mark">وارسی · VARASI</div>
            <div className="report-kind">{model.kind}</div>
          </div>
          <div className="report-stamp">
            {new Date().toLocaleString()}
          </div>
        </div>

        <h1 className="report-title">{model.title}</h1>
        {model.subtitle && <div className="report-sub">{model.subtitle}</div>}
        {model.dateRange && <div className="report-range">{model.dateRange}</div>}

        {/* Meta grid */}
        <div className="report-meta">
          {model.meta.map((m) => (
            <div key={m.label} className="report-meta-item">
              <div className="report-meta-label">{m.label}</div>
              <div className="report-meta-value">{m.value}</div>
            </div>
          ))}
        </div>

        {/* Map snapshot */}
        {model.mapImage && (
          <div className="report-map">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={model.mapImage} alt="map" />
          </div>
        )}

        {/* Stats */}
        {model.stats && model.stats.length > 0 && (
          <div className="report-stats">
            {model.stats.map((s) => (
              <div key={s.label} className="report-stat">
                <div className="report-stat-value">{s.value}</div>
                <div className="report-stat-label">{s.label}</div>
              </div>
            ))}
          </div>
        )}

        {/* Class breakdown bars */}
        {model.classBreakdown && model.classBreakdown.length > 0 && (
          <div className="report-section">
            <div className="report-section-title">Change by class</div>
            {model.classBreakdown.map((c) => (
              <div key={c.class} className="report-bar-row">
                <span className="report-bar-label">
                  <span className="report-dot" style={{ background: CLASS_COLOR[c.class] ?? "#757847" }} />
                  {c.class.replace(/_/g, " ")}
                </span>
                <span className="report-bar-track">
                  <span
                    className="report-bar-fill"
                    style={{ width: `${(c.area_m2 / maxClass) * 100}%`, background: CLASS_COLOR[c.class] ?? "#757847" }}
                  />
                </span>
                <span className="report-bar-value">{km2(c.area_m2)} km²</span>
              </div>
            ))}
          </div>
        )}

        <div className="report-foot">
          {model.footerNote ?? "Generated by Varasi — geospatial change detection."}
        </div>
      </div>
    </div>
  );
}
